import prettierPlugin from 'eslint-plugin-prettier';

export default [
  {
    files: ['**/*.js'],
    ignores: [
      'node_modules/**',
      'js/**',
      '.debug/**',
      'playwright-report/**',
      'test-results/**',
      '.cursor/**',
      '.vscode/**',
    ],
    languageOptions: {
      sourceType: 'module',
      ecmaVersion: 2021,
      globals: {
        window: 'readonly',
        document: 'readonly',
        console: 'readonly',
        navigator: 'readonly',
        frameCount: 'readonly',
        sin: 'readonly',
        cos: 'readonly',
        random: 'readonly',
        sqrt: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        fetch: 'readonly',
        require: 'readonly',
        module: 'readonly',
        __dirname: 'readonly',
        process: 'readonly',
        drawGlow: 'readonly',
        visualEffectsManager: 'readonly',
        SpeechSynthesisUtterance: 'readonly',
        localStorage: 'readonly',
        CustomEvent: 'readonly',
        constrain: 'readonly',
        dist: 'readonly',
        CLOSE: 'readonly',
        global: 'readonly',
        beforeAll: 'readonly',
        MouseEvent: 'readonly',
      },
    },
    plugins: {
      prettier: prettierPlugin,
    },
    rules: {
      'prefer-const': 'error',
      'no-var': 'error',
      'no-undef': 'error',
      'prettier/prettier': 'error',
    },
  },
];
