// playTone's fade-in. Every tone must be comfortably longer than this, or the
// decay's end lands before the attack's and the tone is silent or clicks.
export const TONE_ATTACK_SEC = 0.01;

export const SOUND_CONFIG = {
  playerShoot: {
    frequency: 220,
    waveform: 'sawtooth',
    volume: 0.2,
    duration: 0.04,
  },
  alienShoot: {
    frequency: 950,
    waveform: 'square',
    volume: 0.25,
    duration: 0.08,
    frequencyVariationRange: 0.06,
  },
  // The tank's shot: a nuclear boom (reverb tail via AMBIENT_SOUNDS) plus
  // two zaps 3% apart, whose beating is the electric buzz. The zaps start at
  // 1.2 kHz, below the stabbers' band, and fall fast
  tankEnergy: {
    frequency: 90,
    waveform: 'square',
    volume: 0.8,
    duration: 0.7,
    sweep: { to: 32, curve: 'exponential' },
  },
  // A tank ball killing an enemy on its way: short, dry, not the shot's boom
  tankBallKill: {
    frequency: 90,
    waveform: 'square',
    volume: 0.7,
    duration: 0.3,
    sweep: { to: 40, curve: 'exponential' },
  },
  tankZap: {
    frequency: 1200,
    waveform: 'sawtooth',
    volume: 0.3,
    duration: 0.45,
    sweep: { to: 90, curve: 'exponential' },
    frequencyVariationRange: 0.02, // keep the detune against tankArc near 3%
  },
  tankArc: {
    frequency: 1236,
    waveform: 'square',
    volume: 0.2,
    duration: 0.45,
    sweep: { to: 92.7, curve: 'exponential' }, // 3% above the zap all the way
    frequencyVariationRange: 0.02,
  },
  stabAttack: {
    frequency: 2200,
    waveform: 'triangle',
    volume: 0.3,
    duration: 0.05,
  },
  explosion: {
    frequency: 180,
    waveform: 'sawtooth',
    volume: 0.7,
    duration: 0.4,
    sweep: { to: 60, curve: 'exponential' },
  },
  hit: { frequency: 1200, waveform: 'triangle', duration: 0.05, volume: 0.4 },
  shieldBreak: {
    frequency: 1800,
    waveform: 'square',
    volume: 0.35,
    duration: 0.25,
    sweep: { to: 300, curve: 'exponential' },
  },
  shieldUp: {
    frequency: 400,
    waveform: 'triangle',
    volume: 0.3,
    duration: 0.3,
    sweep: { to: 1600, curve: 'exponential' },
  },
  playerHit: {
    frequency: 250,
    waveform: 'sawtooth',
    volume: 0.4,
    duration: 0.3,
  },
  rusherScream: {
    frequency: 750,
    waveform: 'sawtooth',
    volume: 0.4,
    duration: 0.4,
    sweep: { to: 150, curve: 'exponential' },
  },
  enemyFrying: {
    frequency: 1400,
    waveform: 'noise',
    duration: 0.3,
    volume: 0.3,
  },
  stabberDash: {
    frequency: 2200,
    waveform: 'triangle',
    volume: 0.35,
    duration: 0.05,
  },
  plasmaCloud: {
    frequency: 75,
    waveform: 'sawtooth',
    volume: 0.8,
    duration: 5.0,
    tremolo: true,
  },
  tankCharging: {
    frequency: 70,
    waveform: 'square',
    volume: 0.4,
    duration: 0.8,
    tremolo: true,
    sweep: { to: 45, curve: 'exponential' },
  },
  tankPower: {
    frequency: 80,
    waveform: 'square',
    volume: 0.5,
    duration: 0.3,
    sweep: { to: 35, curve: 'exponential' },
  },
  stabberChant: {
    frequency: 2000,
    waveform: 'triangle',
    volume: 0.25,
    duration: 0.08,
  },
  gruntAdvance: {
    frequency: 400,
    waveform: 'square',
    volume: 0.2,
    duration: 0.2,
  },
  gruntRetreat: {
    frequency: 350,
    waveform: 'square',
    volume: 0.25,
    duration: 0.08,
  },
  rusherCharge: {
    frequency: 700,
    waveform: 'sawtooth',
    volume: 0.5,
    duration: 0.4,
    tremolo: true,
    sweep: { to: 120, curve: 'exponential' },
  },
  stabberKnife: {
    frequency: 2400,
    waveform: 'triangle',
    volume: 0.35,
    duration: 0.05,
  },
  enemyIdle: { frequency: 200, waveform: 'sine', volume: 0.2, duration: 0.8 },
  tankPowerUp: {
    frequency: 60,
    waveform: 'square',
    volume: 0.5,
    duration: 0.4,
    tremolo: true,
    sweep: { to: 100, curve: 'exponential' },
  },
  stabberStalk: {
    frequency: 1800,
    waveform: 'triangle',
    volume: 0.2,
    duration: 0.08,
  },
  gruntPop: {
    frequency: 1200,
    waveform: 'triangle',
    volume: 0.4,
    duration: 0.08,
  },
  enemyOhNo: {
    frequency: 800,
    waveform: 'sawtooth',
    volume: 0.35,
    duration: 0.4,
    sweep: { to: 200, curve: 'exponential' },
  },
  stabberOhNo: {
    frequency: 1400,
    waveform: 'triangle',
    volume: 0.3,
    duration: 0.35,
    sweep: { to: 300, curve: 'exponential' },
  },
  rusherOhNo: {
    frequency: 1000,
    waveform: 'sawtooth',
    volume: 0.4,
    duration: 0.5,
    sweep: { to: 150, curve: 'exponential' },
  },
  tankOhNo: {
    frequency: 600,
    waveform: 'sawtooth',
    volume: 0.5,
    duration: 0.6,
    sweep: { to: 80, curve: 'exponential' },
  },
  gruntMalfunction: {
    frequency: 180,
    waveform: 'sawtooth',
    volume: 0.25,
    duration: 0.4,
  },
  gruntBeep: {
    frequency: 800,
    waveform: 'triangle',
    volume: 0.25,
    duration: 0.15,
  },
  gruntWhir: { frequency: 300, waveform: 'sine', volume: 0.25, duration: 0.6 },
  gruntError: {
    frequency: 220,
    waveform: 'square',
    volume: 0.25,
    duration: 0.2,
  },
  gruntGlitch: {
    frequency: 150,
    waveform: 'sawtooth',
    volume: 0.25,
    duration: 0.25,
  },
  gruntOw: {
    frequency: 600,
    waveform: 'triangle',
    volume: 0.25,
    duration: 0.18,
  },
  gruntHit: {
    frequency: 450,
    type: 'square',
    waveform: 'square',
    volume: 0.2,
    duration: 0.06,
  },
  tankHit: {
    frequency: 55,
    waveform: 'square',
    volume: 0.35,
    duration: 0.2,
  },
  stabberHit: {
    frequency: 2100,
    type: 'triangle',
    waveform: 'triangle',
    volume: 0.3,
    duration: 0.04,
  },
  rusherHit: {
    frequency: 650,
    type: 'sawtooth',
    waveform: 'sawtooth',
    volume: 0.3,
    duration: 0.08,
  },
  stabberKnifeExtend: {
    frequency: 1800,
    waveform: 'triangle',
    volume: 0.3,
    duration: 0.05,
    sweep: { to: 2500, curve: 'linear' },
  },
  stabberKnifeHit: {
    frequency: 2200,
    waveform: 'triangle',
    volume: 0.4,
    duration: 0.05,
  },
  playerDash: {
    frequency: 200,
    waveform: 'noise',
    volume: 0.3,
    duration: 0.15,
  },
  levelUp: {
    frequency: 440,
    waveform: 'triangle',
    volume: 0.5,
    duration: 0.6,
    sweep: { to: 880, curve: 'exponential' },
  },
  gameOver: {
    frequency: 400,
    waveform: 'sawtooth',
    volume: 0.6,
    duration: 1.0,
    sweep: { to: 60, curve: 'exponential' },
  },
  lowHealthWarning: {
    frequency: 200,
    waveform: 'square',
    volume: 0.2,
    duration: 0.3,
  },
  killStreak: {
    frequency: 660,
    waveform: 'triangle',
    volume: 0.35,
    duration: 0.3,
    sweep: { to: 990, curve: 'linear' },
  },
  gruntResponse: {
    frequency: 380,
    type: 'square',
    waveform: 'square',
    volume: 0.2,
    duration: 0.1,
  },
  tankResponse: {
    frequency: 70,
    waveform: 'square',
    volume: 0.3,
    duration: 0.3,
  },
  stabberResponse: {
    frequency: 2300,
    type: 'triangle',
    waveform: 'triangle',
    volume: 0.25,
    duration: 0.06,
  },
  rusherResponse: {
    frequency: 720,
    type: 'sawtooth',
    waveform: 'sawtooth',
    volume: 0.25,
    duration: 0.15,
    sweep: { to: 500, curve: 'exponential' },
  },
};
