export const SOUND_METHOD_TO_KEY = {
  playPlayerShoot: 'playerShoot',
  playAlienShoot: 'alienShoot',
  playExplosion: 'explosion',
  playHit: 'hit',
  playPlayerHit: 'playerHit',
  playEnemyHit: 'hit',
  playRusherScream: 'rusherScream',
  playTankEnergyBall: 'tankEnergy',
  playStabAttack: 'stabAttack',
  playEnemyFrying: 'enemyFrying',
  playPlasmaCloud: 'plasmaCloud',
  playTankCharging: 'tankCharging',
  playTankPower: 'tankPower',
  playStabberChant: 'stabberChant',
  playGruntAdvance: 'gruntAdvance',
  playGruntRetreat: 'gruntRetreat',
  playRusherCharge: 'rusherCharge',
  playStabberKnife: 'stabberKnife',
  playEnemyIdle: 'enemyIdle',
  playTankPowerUp: 'tankPowerUp',
  playStabberStalk: 'stabberStalk',
  playStabberDash: 'stabberDash',
  playGruntMalfunction: 'gruntMalfunction',
  playGruntBeep: 'gruntBeep',
  playGruntWhir: 'gruntWhir',
  playGruntError: 'gruntError',
  playGruntGlitch: 'gruntGlitch',
  playGruntPop: 'gruntPop',
  playEnemyOhNo: 'enemyOhNo',
  playStabberOhNo: 'stabberOhNo',
  playRusherOhNo: 'rusherOhNo',
  playTankOhNo: 'tankOhNo',
  playBombExplosion: 'explosion',
  playRusherExplosion: 'explosion',
  playStabberAttack: 'stabAttack',
};

export const SOUND_CONFIG = {
  playerShoot: {
    frequency: 480,
    waveform: 'sawtooth',
    volume: 0.2,
    duration: 0.01,
  },
  alienShoot: {
    frequency: 800,
    waveform: 'square',
    volume: 0.25,
    duration: 0.15,
  },
  tankEnergy: { frequency: 80, waveform: 'sine', volume: 0.7, duration: 1.0 },
  stabAttack: {
    frequency: 2000,
    waveform: 'sawtooth',
    volume: 0.3,
    duration: 0.1,
  },
  explosion: {
    frequency: 250,
    waveform: 'sawtooth',
    volume: 0.7,
    duration: 0.3,
  },
  hit: { frequency: 1200, waveform: 'triangle', duration: 0.05, volume: 0.2 },
  playerHit: {
    frequency: 250,
    waveform: 'sawtooth',
    volume: 0.4,
    duration: 0.3,
  },
  rusherScream: {
    frequency: 800,
    waveform: 'sawtooth',
    volume: 0.4,
    duration: 1.0,
  },
  enemyFrying: {
    frequency: 1400,
    waveform: 'noise',
    duration: 0.3,
    volume: 0.3,
  },
  stabberDash: {
    frequency: 2500,
    waveform: 'sawtooth',
    volume: 0.4,
    duration: 0.3,
  },
  plasmaCloud: {
    frequency: 75,
    waveform: 'sawtooth',
    volume: 0.8,
    duration: 5.0,
  },
  tankCharging: {
    frequency: 60,
    waveform: 'sawtooth',
    volume: 0.4,
    duration: 0.8,
  },
  tankPower: {
    frequency: 40,
    waveform: 'sawtooth',
    volume: 0.5,
    duration: 1.2,
  },
  stabberChant: {
    frequency: 1800,
    waveform: 'triangle',
    volume: 0.3,
    duration: 0.5,
  },
  gruntAdvance: {
    frequency: 400,
    waveform: 'square',
    volume: 0.2,
    duration: 0.2,
  },
  gruntRetreat: {
    frequency: 350,
    waveform: 'square',
    volume: 0.15,
    duration: 0.08,
  },
  rusherCharge: {
    frequency: 1200,
    waveform: 'sawtooth',
    volume: 0.5,
    duration: 0.6,
    tremolo: true,
  },
  stabberKnife: {
    frequency: 2200,
    waveform: 'triangle',
    volume: 0.4,
    duration: 0.15,
  },
  enemyIdle: { frequency: 200, waveform: 'sine', volume: 0.1, duration: 0.8 },
  tankPowerUp: {
    frequency: 40,
    waveform: 'sawtooth',
    volume: 0.5,
    duration: 1.2,
  },
  stabberStalk: {
    frequency: 1600,
    waveform: 'triangle',
    volume: 0.25,
    duration: 0.4,
  },
  gruntPop: {
    frequency: 1200,
    waveform: 'triangle',
    volume: 0.4,
    duration: 0.08,
  },
  enemyOhNo: {
    frequency: 800,
    waveform: 'sawtooth',
    volume: 0.35,
    duration: 0.4,
    sweep: { to: 200, curve: 'exponential' },
  },
  stabberOhNo: {
    frequency: 1400,
    waveform: 'triangle',
    volume: 0.3,
    duration: 0.35,
    sweep: { to: 300, curve: 'exponential' },
  },
  rusherOhNo: {
    frequency: 1000,
    waveform: 'sawtooth',
    volume: 0.4,
    duration: 0.5,
    sweep: { to: 150, curve: 'exponential' },
  },
  tankOhNo: {
    frequency: 600,
    waveform: 'sawtooth',
    volume: 0.5,
    duration: 0.6,
    sweep: { to: 80, curve: 'exponential' },
  },
  gruntMalfunction: {
    frequency: 180,
    waveform: 'sawtooth',
    volume: 0.12,
    duration: 0.4,
  },
  gruntBeep: {
    frequency: 800,
    waveform: 'triangle',
    volume: 0.08,
    duration: 0.15,
  },
  gruntWhir: { frequency: 300, waveform: 'sine', volume: 0.1, duration: 0.6 },
  gruntError: {
    frequency: 220,
    waveform: 'square',
    volume: 0.1,
    duration: 0.2,
  },
  gruntGlitch: {
    frequency: 150,
    waveform: 'sawtooth',
    volume: 0.09,
    duration: 0.25,
  },
  gruntOw: {
    frequency: 600,
    waveform: 'triangle',
    volume: 0.25,
    duration: 0.18,
  },
};
