name: CI - Dev Server & Probes

on:
  push:
    branches: [unstable, main]
  pull_request:
    branches: [unstable, main]

jobs:
  probe-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        bun-version: ['latest']

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ matrix.bun-version }}

      - name: Cache Bun global cache
        uses: actions/cache@v3
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('bun.lock') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Cache Playwright browsers
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/ms-playwright
            ~/.ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('package.json', 'bun.lock') }}
          restore-keys: |
            ${{ runner.os }}-playwright-

      - name: Install Playwright browsers
        run: bunx playwright install --with-deps

      - name: Start dev environment
        run: bun run dev:start

      - name: Dev status (sanity check)
        run: bun run dev:status

      - name: Run Playwright probes
        run: bunx playwright test --reporter=line | cat

      - name: Stop dev environment
        if: always()
        run: bun run dev:stop

      - name: Doc drift guard
        run: bun run ci:check-doc-drift

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-${{ matrix.os }}
          path: playwright-report/
          if-no-files-found: ignore 