name: Learning Tuner (Nightly)

on:
  schedule:
    - cron: '0 4 * * *' # Daily at 04:00 UTC
  workflow_dispatch:

jobs:
  tuner:
    runs-on: windows-latest
    timeout-minutes: 60
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install deps
        run: bun install --frozen-lockfile
        shell: cmd

      - name: Create branch
        run: git checkout -b chore/tune-$(Get-Date -Format yyyyMMdd-HHmmss)
        shell: powershell

      - name: Run tuner (lodMultiplier)
        run: bun run learn:tune "packages/fx/src/effectsConfig.js:global.lodMultiplier"
        shell: cmd

      - name: Run tuner (explosion particleMultiplier)
        run: bun run learn:tune "packages/core/src/fxConfig.js:explosionFX.particleMultiplier"
        shell: cmd

      - name: Commit tuning artifacts
        run: |
          git add -A
          git diff --cached --quiet || git commit -m "chore: tuning report(s)"
        shell: bash

      - name: Push branch
        run: git push --set-upstream origin HEAD
        shell: bash

      - name: Open PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_BASE: unstable
          PR_TITLE: 'chore: nightly tuning reports'
          PR_BODY: 'Nightly tuning reports generated by learning system. No code changes beyond reports unless a variant is selected manually.'
        run: bun run scripts/learning/open-pr.js
        shell: cmd

      - name: Upload tuning reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: tuning-reports
          path: .ai/metrics
