name: Learning AutoFix (Daily)

on:
  schedule:
    - cron: '30 3 * * *' # Daily at 03:30 UTC
  workflow_dispatch:

jobs:
  autofix:
    runs-on: windows-latest
    timeout-minutes: 40
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install deps
        run: bun install --frozen-lockfile
        shell: cmd

      - name: Create branch
        run: git checkout -b chore/auto-fix-$(Get-Date -Format yyyyMMdd-HHmmss)
        shell: powershell

      - name: Run conservative auto-fix
        run: bun run learn:fix
        shell: cmd

      - name: Commit changes if any
        run: |
          git add -A
          git diff --cached --quiet || git commit -m "chore: automated autofix (PI/TWO_PI, dist imports)"
        shell: bash

      - name: Push branch
        run: git push --set-upstream origin HEAD
        shell: bash

      - name: Open PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_BASE: unstable
          PR_TITLE: 'chore: automated conservative autofix'
          PR_BODY: 'This PR is auto-generated by the learning system. Includes conservative transforms only (PI/TWO_PI replacements and missing dist imports).'
        run: bun run scripts/learning/open-pr.js
        shell: cmd
