name: CI (PR)

on:
  pull_request:
    branches: [ unstable, main ]

jobs:
  build-and-test:
    runs-on: windows-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install deps
        run: bun install --frozen-lockfile
        shell: cmd

      - name: Lint (ESLint)
        run: bun run lint
        shell: cmd

      - name: Consistency scan
        run: bun run scan:consistency
        shell: cmd

      - name: Secrets scan
        run: bun run scan:secrets
        shell: cmd

      - name: Validate sounds
        run: bun run validate:sounds
        shell: cmd

      - name: Orchestrated Playwright tests
        run: bun run test:orchestrated
        shell: cmd
        env:
          ELECTRON_RUN_AS_NODE: ""

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results
