name: CodeRabbit Fetch (PR + Nightly)

on:
  pull_request:
    types: [synchronize]
  schedule:
    - cron: '0 7 * * *' # daily 07:00 UTC

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Install
        run: bun install --no-cache
      - name: Fetch latest CodeRabbit items
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bun run coderabbit:fetch-latest
      - name: Upload actionable summary
        uses: actions/upload-artifact@v4
        with:
          name: coderabbit-actionable-summary
          path: coderabbit-reviews/actionable-summary.json


