name: Secret Scan

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

jobs:
  secret-scan:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Run secret scanner
        run: bun run scan:secrets --all
